project:
  type: website

execute:
  ipynb-shell-interactivity: all
  

format:
  html:
    css: styles.css
    toc: true
    # For proper retina (similar to what we get in the notebook),
    # double the default dpi, then using CSS maintain the default size
    fig-dpi: 200

website:
  navbar:
    left:
      - file: index.qmd
      - file: guide/intro.qmd
        text: "Guide"
  sidebar:
    - title: Guide
      contents:
        - guide/intro.qmd
        - guide/overview.qmd
        - section: "BASICS"
          contents:
          - guide/aesthetic-mappings.qmd
          - guide/geometric-objects.qmd
          - guide/scale-basics.qmd
          - guide/position-adjustments.qmd
          - guide/facets.qmd
          - guide/coordinate-systems.qmd
        - section: "POLISHING"
          contents:
          - guide/export.qmd
          - guide/labels.qmd
          - guide/annotations.qmd
        - section: "THEMING"
          contents:
          - guide/themes-basics.qmd
          - guide/themes-premade.qmd
          - guide/themes-custom.qmd
        # - section: "Scales"
        #   contents:
        #   - guide/scale-x-and-y.qmd
        #   - guide/scale-color-fill.qmd
        #   - guide/scale-misc.qmd
        - section: "CASE STUDIES"
          contents:
          - guide/case-study1.qmd
          - guide/case-study2.qmd
          - guide/case-study3.qmd
        - section: "UNSORTED"
          contents:
          - guide/maps.qmd
          - guide/shortcuts.qmd
          - guide/misc.qmd
          - guide/feature-coverage.qmd
          - guide/aesthetic-specification.qmd
    - id: dummy


