project:
  type: website
  pre-render:
    - uv run homepage/bin/render.sh
  render:
    - "index.qmd"
    - "gallery/*.qmd"
    - "test.qmd"
    - "!demo/"
    - "guide/"
  post-render:
    - "cp -r demo _site/"
    - "sed -e /bootstrap.*css/d -i.bak _site/index.html"

metadata-files:
  - guide/_sidebar.yml

format:
  html:
    theme:
      - lumen
      - plotnine.scss

website:
  title: Plotnine
  navbar:
    left:
      - file: guide/install.qmd
        text: "Guide"
      - text: "Reference"
        href: https://plotnine.org/reference/
      - text: "Gallery"
        href: https://plotnine.org/gallery/
      - text: "Blog"
        href: https://plotnine.org/blog.html
  sidebar:
    - id: dummy


