project:
  type: website


format:
  html:
    css: styles.css
    toc: true
    # For proper retina (similar to what we get in the notebook),
    # double the default dpi, then using CSS maintain the default size
    fig-dpi: 200

website:
  navbar:
    left:
      - file: index.qmd
      - file: guide/intro.qmd
        text: "Guide"
  sidebar:
    - title: Guide
      contents:
        - guide/intro.qmd
        - guide/overview.qmd
        - section: "Basics"
          contents:
          - guide/aesthetic-mappings.qmd
          - guide/geometric-objects.qmd
          - guide/scale-basics.qmd
          - guide/position-adjustments.qmd
          - guide/facets.qmd
          - guide/coordinate-systems.qmd
        - section: "Polishing"
          contents:
          - guide/labels.qmd
          - guide/annotations.qmd
          - guide/themes.qmd
        - section: "Scales"
          contents:
          - guide/scale-x-and-y.qmd
          - guide/scale-color-fill.qmd
          - guide/scale-misc.qmd
        - section: "Export"
          contents:
          - guide/export.qmd
    - id: dummy


